# Generated by Django 3.1.4 on 2022-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0002_auto_20221212_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='anmerkungen',
            field=models.TextField(blank=True),
        ),
    ]
