# Generated by Django 3.1.4 on 2022-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0003_auto_20221212_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='art_zutaten',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='bewertung',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kueche',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='portionen',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='zubereitung',
            field=models.TextField(blank=True),
        ),
    ]
