# Generated by Django 3.1.4 on 2022-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0004_auto_20221212_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='bewertung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='portionen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
