# Generated by Django 3.1.4 on 2022-12-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0005_auto_20221212_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speisenart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
