# Generated by Django 3.1.4 on 2022-12-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0006_speisenart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezept',
            options={'verbose_name_plural': 'Rezepte'},
        ),
        migrations.AlterModelOptions(
            name='speisenart',
            options={'verbose_name_plural': 'Speisenarten'},
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.speisenart'),
        ),
    ]
