# Generated by Django 3.1.4 on 2022-12-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0008_auto_20221219_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezept',
            options={'verbose_name_plural': 'rezepte'},
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.speisenart'),
        ),
    ]
