# Generated by Django 3.1.4 on 2022-12-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0009_auto_20221219_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kueche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Küchen',
            },
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kueche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.kueche'),
        ),
    ]
