# Generated by Django 3.1.4 on 2022-12-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0011_auto_20221222_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='kueche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.kueche'),
        ),
    ]
