# Generated by Django 3.1.4 on 2023-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0017_auto_20230112_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='kategorie',
            field=models.CharField(choices=[('VORSP', 'Vorspeise, Zwischengericht'), ('SUPPE', 'Suppe')], max_length=80),
        ),
    ]
