# Generated by Django 3.1.4 on 2023-01-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0018_auto_20230118_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='art_zutaten',
            field=models.CharField(blank=True, choices=[('Fleisch', 'Fleisch'), ('Fleisch - Huhn', 'Fleisch - Huhn'), ('vegetarisch', 'vegetarisch'), ('vegetarisch - Pasta', 'vegetarisch - Pasta')], max_length=80),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kategorie',
            field=models.CharField(choices=[('Vorspeise, Zwischengericht', 'Vorspeise, Zwischengericht'), ('Suppe', 'Suppe'), ('Hauptspeise', 'Hauptspeise'), ('Beilage', 'Beilage'), ('Salat', 'Salat'), ('Nachspeise', 'Nachspeise'), ('Brot, Gebäck', 'Brot, Gebäck'), ('Sauce, Dipp', 'Sauce, Dipp'), ('Torte, Kuchen', 'Torte, Kuchen'), ('Kekse', 'Kekse')], max_length=80),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kueche',
            field=models.CharField(blank=True, choices=[('österreichisch', 'österreichisch'), ('italienisch', 'italienisch'), ('thailändisch', 'thailändisch'), ('chinesisch', 'chinesisch'), ('französisch', 'französisch')], max_length=80),
        ),
    ]
