# Generated by Django 3.1.4 on 2023-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0019_auto_20230118_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='vegetarisch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='art_zutaten',
            field=models.CharField(blank=True, choices=[('Fleisch', 'Fleisch'), ('Fleisch - Schwein', 'Fleisch - Schwein'), ('Fleisch - Rind', 'Fleisch - Rind'), ('Fleisch - Lamm', 'Fleisch - Lamm'), ('Fleisch - Huhn, Geflügel', 'Fleisch - Huhn, Geflügel'), ('Fleisch - Wild', 'Fleisch - Wild'), ('Pasta', 'Pasta'), ('vegetarisch', 'vegetarisch'), ('vegetarisch - Pasta', 'vegetarisch - Pasta'), ('vegetarisch - Gemüse', 'vegetarisch - Gemüse'), ('vegetarisch - Mehlspeise', 'vegetarisch - Mehlspeise'), ('Fisch, Meeresfrüchte', 'Fisch, Meeresfrüchte')], max_length=80),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='portionen',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
    ]
